# Generated by Django 4.0.4 on 2022-05-11 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='owner',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='djangiapi', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='words',
            name='defn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
