# Generated by Django 4.0.4 on 2022-05-11 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoapi', '0002_words_owner_alter_words_defn_alter_words_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='defn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='words',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
