# Generated by Django 4.0.4 on 2022-05-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='en_words',
            new_name='word',
        ),
    ]
