# Generated by Django 4.0.4 on 2022-05-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0002_rename_en_words_words_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_words2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word9', models.CharField(max_length=200)),
                ('defn9', models.CharField(max_length=200)),
            ],
        ),
    ]
