# Generated by Django 4.0.4 on 2022-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0003_test_words2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_words2',
        ),
        migrations.AlterField(
            model_name='words',
            name='defn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
