# Generated by Django 4.0.4 on 2022-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.TextField(),
        ),
    ]
