# Generated by Django 4.0.4 on 2022-05-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dic',
            new_name='dict',
        ),
    ]
