# Generated by Django 4.0.4 on 2022-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordic', '0002_rename_dic_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='date_word',
        ),
        migrations.AlterField(
            model_name='dict',
            name='defn_word',
            field=models.CharField(max_length=100, verbose_name='te'),
        ),
    ]
